# brand_analyser.py
# This script reads the completed brand intake JSON file,
# sends all answers to Claude for analysis, and produces
# a structured brand voice document as the output.
# This is the client-facing strategic deliverable for Project 2.

import anthropic
import json
import os
from datetime import datetime

# Set up the Anthropic client.
client = anthropic.Anthropic()

# ── Load the intake answers ──────────────────────────────────────────────────

def load_intake_answers(filepath):
    """
    Loads the brand intake answers from the JSON file.

    Parameters:
        filepath (str): Path to the JSON file.

    Returns:
        dict: The full set of intake answers.
    """

    # Open the JSON file and parse it back into a Python dictionary.
    # This is the reverse of what json.dump() did in Step 1.
    with open(filepath, "r", encoding="utf-8") as f:
        return json.load(f)


# ── Format answers for Claude ────────────────────────────────────────────────

def format_answers_for_prompt(intake_data):
    """
    Converts the JSON intake data into a clean, readable text block
    that Claude can process easily in a prompt.

    Parameters:
        intake_data (dict): The loaded intake answers dictionary.

    Returns:
        str: A formatted string of all questions and answers.
    """

    # Start with the brand name and interview date as context.
    formatted = f"BRAND: {intake_data['brand_name']}\n"
    formatted += f"INTERVIEW DATE: {intake_data['interview_date']}\n\n"

    # Loop through each category and its answers.
    for category in intake_data["categories"]:
        formatted += f"{'─' * 40}\n"
        formatted += f"CATEGORY: {category['category'].upper()}\n"
        formatted += f"{'─' * 40}\n"

        # Loop through each question and answer pair.
        for i, qa in enumerate(category["answers"], start=1):
            formatted += f"Q{i}: {qa['question']}\n"
            formatted += f"A: {qa['answer']}\n\n"

    return formatted


# ── Brand voice analysis function ────────────────────────────────────────────

def analyse_brand_voice(intake_data):
    """
    Sends the formatted intake answers to Claude and returns
    a complete brand voice document.

    Parameters:
        intake_data (dict): The loaded intake answers dictionary.

    Returns:
        str: The full brand voice document generated by Claude.
    """

    # Format the answers into a readable text block for the prompt.
    formatted_answers = format_answers_for_prompt(intake_data)

    # The system prompt sets Claude's role for this task.
    system_prompt = """
    You are a senior brand strategist with deep expertise in DTC eCommerce brands.
    You specialise in translating founder interviews and brand discovery sessions
    into clear, actionable brand voice documents that marketing teams and AI systems
    can use to produce consistent, on-brand content.

    Your documents are known for being specific and practical — not vague or generic.
    Every guideline you write includes a concrete example so the reader knows
    exactly what it means in practice.

    You write with authority and clarity. No filler. No corporate language.
    """

    # The user prompt sends the intake answers and specifies exactly
    # what document structure Claude should produce.
    user_prompt = f"""
    Below are the answers from a brand discovery interview with {intake_data['brand_name']}.
    
    Analyse these answers thoroughly and produce a complete Brand Voice Document
    using the exact structure specified below.

    INTERVIEW ANSWERS:
    {formatted_answers}

    PRODUCE THE FOLLOWING DOCUMENT STRUCTURE — use these exact section headers:

    1. BRAND POSITIONING STATEMENT
    Write a single sharp paragraph that captures who this brand is,
    who they serve, and what makes them different. Max 80 words.

    2. BRAND PERSONALITY
    List 5 personality traits with a one-sentence description of what
    each trait means for this brand specifically. Not generic definitions.

    3. TARGET AUDIENCE PROFILE
    Write a detailed profile of the ideal customer. Include demographics,
    psychographics, what they value, what frustrates them, and what they
    want to feel when they interact with this brand.

    4. VOICE AND TONE GUIDELINES
    Provide 6 specific writing rules for this brand. Each rule must include:
    - The rule stated clearly
    - A DO example (a sentence written correctly in this brand's voice)
    - A DON'T example (the same idea written wrongly)

    5. VOCABULARY GUIDE
    List 10 words or phrases this brand SHOULD use regularly, with a brief
    note on why each fits the brand. Then list 10 words or phrases this brand
    should NEVER use, with a note on why each is wrong for this brand.

    6. CONTENT PILLARS
    Define 4 content pillars for this brand — the core topic areas they
    should consistently create content around. For each pillar include:
    - Pillar name
    - One sentence description
    - 3 specific content ideas that fit this pillar

    7. BRAND VOICE SUMMARY CARD
    Write a condensed one-page reference that captures the essential brand
    voice rules in a format a copywriter or AI system can read quickly
    before writing any content for this brand.

    Be specific to FemFit.fit throughout. Do not write generic brand strategy advice.
    Every section should feel like it could only have been written for this brand.
    """

    response = client.messages.create(
        model="claude-opus-4-5",
        max_tokens=4000,
        system=system_prompt,
        messages=[
            {"role": "user", "content": user_prompt}
        ]
    )

    return response.content[0].text


# ── Save function ────────────────────────────────────────────────────────────

def save_brand_voice_document(content, brand_name):
    """
    Saves the brand voice document to the outputs folder.

    Parameters:
        content (str): The brand voice document text.
        brand_name (str): Used in the filename.

    Returns:
        str: The path to the saved file.
    """

    os.makedirs("outputs", exist_ok=True)

    # Clean the brand name for use in a filename.
    # .replace() swaps spaces for underscores.
    # .replace() also removes the dot from FemFit.fit
    clean_name = brand_name.replace(" ", "_").replace(".", "")

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filepath = f"outputs/{clean_name}_Brand_Voice_Document_{timestamp}.txt"

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(f"BRAND VOICE DOCUMENT\n")
        f.write(f"Brand: {brand_name}\n")
        f.write(f"Generated: {datetime.now().strftime('%d %B %Y, %H:%M')}\n")
        f.write(f"Powered by Claude AI\n")
        f.write("=" * 60 + "\n\n")
        f.write(content)

    return filepath


# ── Main runner ──────────────────────────────────────────────────────────────

if __name__ == "__main__":

    intake_filepath = "outputs/brand_intake_answers.json"

    # Check the intake file exists before trying to load it.
    # If it does not exist, print a helpful error and stop.
    if not os.path.exists(intake_filepath):
        print("ERROR: brand_intake_answers.json not found.")
        print("Run brand_intake.py first to complete the interview.")
        exit()

    print("=" * 60)
    print("FEMFIT.FIT — BRAND VOICE ANALYSER")
    print("Loading intake answers...")
    print("=" * 60)

    # Load the answers from the JSON file.
    intake_data = load_intake_answers(intake_filepath)
    print(f"✓ Loaded answers for: {intake_data['brand_name']}")
    print(f"✓ Interview date: {intake_data['interview_date']}")
    print("\nSending to Claude for analysis...")
    print("This may take 20-30 seconds...\n")

    # Send to Claude and get the brand voice document back.
    brand_voice_doc = analyse_brand_voice(intake_data)

    # Save the document to the outputs folder.
    filepath = save_brand_voice_document(brand_voice_doc, intake_data["brand_name"])

    print(brand_voice_doc)

    print("\n" + "=" * 60)
    print("✓ Brand voice document complete.")
    print(f"✓ Saved to: {filepath}")
    print("Run content_strategy.py next to build the content strategy.")
    print("=" * 60)