# lead_researcher.py
# This script scores each lead against the qualification criteria,
# filters out leads below the threshold, and sends qualified leads
# to Claude for deep research analysis.
# Output is a list of qualified leads with research briefs attached.

import anthropic
import os
import json
from datetime import datetime
from lead_profiles import LEADS, IDEAL_CLIENT_PROFILE, SCORING_CRITERIA, QUALIFICATION_THRESHOLD

client = anthropic.Anthropic()


# ── Lead scorer ──────────────────────────────────────────────────────────────

def score_lead(lead):
    """
    Scores a single lead against the qualification criteria.
    Returns the lead dictionary with score and qualification status added.

    Parameters:
        lead (dict): A lead dictionary from LEADS.

    Returns:
        dict: The lead with qualification_score and qualified fields filled in.
    """

    score = 0
    score_breakdown = {}

    # Check each criterion and add points if met.
    # We use .get() with a default of False for safety.

    # Criterion 1: Uses Shopify
    if lead.get("shopify", False):
        score += SCORING_CRITERIA["uses_shopify"]
        score_breakdown["uses_shopify"] = SCORING_CRITERIA["uses_shopify"]
    else:
        score_breakdown["uses_shopify"] = 0

    # Criterion 2: Has an email platform
    if lead.get("email_platform"):
        score += SCORING_CRITERIA["has_email_platform"]
        score_breakdown["has_email_platform"] = SCORING_CRITERIA["has_email_platform"]
    else:
        score_breakdown["has_email_platform"] = 0

    # Criterion 3: Follower count in ideal range (1k to 50k)
    followers = lead.get("instagram_followers", 0)
    if 1000 <= followers <= 50000:
        score += SCORING_CRITERIA["follower_range_1k_to_50k"]
        score_breakdown["follower_range_1k_to_50k"] = SCORING_CRITERIA["follower_range_1k_to_50k"]
    else:
        score_breakdown["follower_range_1k_to_50k"] = 0

    # Criterion 4: Posts regularly
    # We check if the posting frequency string contains a number above 2.
    # This is a simple heuristic — in a real system you would check post dates.
    frequency = lead.get("posting_frequency", "")
    posts_regularly = any(
        str(n) in frequency for n in range(3, 10)
    ) or "daily" in frequency.lower()

    if posts_regularly:
        score += SCORING_CRITERIA["posts_regularly"]
        score_breakdown["posts_regularly"] = SCORING_CRITERIA["posts_regularly"]
    else:
        score_breakdown["posts_regularly"] = 0

    # Criterion 5: Has observable pain points
    pain_points = lead.get("pain_points_observed", [])
    if len(pain_points) >= 2:
        score += SCORING_CRITERIA["has_pain_points"]
        score_breakdown["has_pain_points"] = SCORING_CRITERIA["has_pain_points"]
    else:
        score_breakdown["has_pain_points"] = 0

    # Criterion 6: Has recent activity we can reference
    if lead.get("recent_activity"):
        score += SCORING_CRITERIA["recent_activity_detected"]
        score_breakdown["recent_activity_detected"] = SCORING_CRITERIA["recent_activity_detected"]
    else:
        score_breakdown["recent_activity_detected"] = 0

    # Add score and qualification status to the lead dictionary.
    # We use .copy() to avoid modifying the original LEADS list.
    scored_lead = lead.copy()
    scored_lead["qualification_score"] = score
    scored_lead["score_breakdown"] = score_breakdown
    scored_lead["qualified"] = score >= QUALIFICATION_THRESHOLD

    return scored_lead


# ── Research brief generator ─────────────────────────────────────────────────

def generate_research_brief(lead):
    """
    Sends a qualified lead's data to Claude and returns a research brief.
    The brief summarises the lead's situation and recommends an outreach angle.

    Parameters:
        lead (dict): A scored and qualified lead dictionary.

    Returns:
        str: A research brief generated by Claude.
    """

    # Format the pain points as a readable list for the prompt.
    pain_points_text = "\n".join(
        f"- {point}" for point in lead["pain_points_observed"]
    )

    # Format the score breakdown for context.
    score_text = "\n".join(
        f"- {k.replace('_', ' ').title()}: {v} points"
        for k, v in lead["score_breakdown"].items()
    )

    user_prompt = f"""
    You are a business development researcher for AIMarketer.co — a Claude AI
    Co-Worker Specialist agency that helps Shopify DTC brands automate their
    marketing workflows using AI.

    Analyse the following lead and produce a research brief that will be used
    to write personalised outreach to this brand.

    LEAD INFORMATION:
    Brand: {lead['brand_name']}
    Founder: {lead['founder_name']} ({lead['role']})
    Industry: {lead['industry']}
    Products: {lead['product_focus']}
    Instagram followers: {lead['instagram_followers']:,}
    Email platform: {lead['email_platform']}
    Posting frequency: {lead['posting_frequency']}
    Qualification score: {lead['qualification_score']}/100

    OBSERVED PAIN POINTS:
    {pain_points_text}

    RECENT ACTIVITY:
    {lead['recent_activity']}

    CURRENT CONTENT TONE:
    {lead['tone_of_current_content']}

    PRODUCE A RESEARCH BRIEF WITH THESE SECTIONS:

    SITUATION SUMMARY:
    Two to three sentences summarising where this brand is right now —
    their strengths, their stage of growth, and their primary challenge.

    PRIMARY PAIN POINT:
    The single most pressing marketing problem this brand has, based on
    the observed signals. Be specific — name the exact gap.

    OUTREACH ANGLE:
    The strongest hook for reaching out to this specific brand.
    What is the one thing AIMarketer.co can say that will make
    {lead['founder_name']} stop and pay attention?

    SERVICE FIT:
    Which AIMarketer.co service fits this lead best and why:
    - AI-powered email campaign system
    - Brand voice and content strategy builder
    - AI lead generation and outreach system
    - AI marketing audit and strategy report
    - Social media content engine

    PERSONALISATION HOOKS:
    Three specific details from the lead data that can be referenced
    naturally in the outreach message to show genuine research.

    Keep the entire brief under 300 words. Be specific and direct.
    Do not use generic sales language.
    """

    response = client.messages.create(
        model="claude-opus-4-5",
        max_tokens=800,
        system="You are a precise business development researcher. Your briefs are specific, actionable, and free of generic sales language.",
        messages=[{"role": "user", "content": user_prompt}]
    )

    return response.content[0].text


# ── Save results ─────────────────────────────────────────────────────────────

def save_research_results(scored_leads, qualified_leads_with_briefs):
    """
    Saves both the full scored list and the qualified leads with briefs.

    Parameters:
        scored_leads (list): All leads with scores attached.
        qualified_leads_with_briefs (list): Qualified leads with research briefs.
    """

    os.makedirs("outputs", exist_ok=True)

    # Save the full scored leads list as JSON.
    # This gives us a record of all leads including disqualified ones.
    scored_filepath = "outputs/all_leads_scored.json"
    with open(scored_filepath, "w", encoding="utf-8") as f:
        json.dump(scored_leads, f, indent=2, ensure_ascii=False)

    # Save the qualified leads with briefs as JSON.
    # This is what the outreach generator reads in Step 3.
    qualified_filepath = "outputs/qualified_leads_with_briefs.json"
    with open(qualified_filepath, "w", encoding="utf-8") as f:
        json.dump(qualified_leads_with_briefs, f, indent=2, ensure_ascii=False)

    # Save a human-readable summary as a text file.
    summary_filepath = "outputs/lead_research_summary.txt"
    with open(summary_filepath, "w", encoding="utf-8") as f:

        f.write("=" * 60 + "\n")
        f.write("AIMARKETER.CO — LEAD RESEARCH SUMMARY\n")
        f.write(f"Generated: {datetime.now().strftime('%d %B %Y, %H:%M')}\n")
        f.write("=" * 60 + "\n\n")

        f.write(f"LEADS PROCESSED: {len(scored_leads)}\n")
        f.write(f"LEADS QUALIFIED: {len(qualified_leads_with_briefs)}\n")
        f.write(f"QUALIFICATION THRESHOLD: {QUALIFICATION_THRESHOLD}/100\n\n")

        f.write("─" * 60 + "\n")
        f.write("SCORING RESULTS\n")
        f.write("─" * 60 + "\n\n")

        for lead in scored_leads:
            status = "✓ QUALIFIED" if lead["qualified"] else "✗ DISQUALIFIED"
            f.write(f"{lead['brand_name']} — {lead['qualification_score']}/100 — {status}\n")

        f.write("\n" + "─" * 60 + "\n")
        f.write("QUALIFIED LEAD RESEARCH BRIEFS\n")
        f.write("─" * 60 + "\n")

        for lead in qualified_leads_with_briefs:
            f.write(f"\n{'=' * 60}\n")
            f.write(f"LEAD: {lead['brand_name']} ({lead['id']})\n")
            f.write(f"Contact: {lead['founder_name']} — {lead['role']}\n")
            f.write(f"Score: {lead['qualification_score']}/100\n")
            f.write(f"{'─' * 40}\n")
            f.write(lead["research_brief"])
            f.write(f"\n{'─' * 60}\n")

    print(f"✓ All leads scored: {scored_filepath}")
    print(f"✓ Qualified leads with briefs: {qualified_filepath}")
    print(f"✓ Human-readable summary: {summary_filepath}")


# ── Main runner ──────────────────────────────────────────────────────────────

if __name__ == "__main__":

    print("=" * 60)
    print("AIMARKETER.CO — LEAD RESEARCHER AND SCORING ENGINE")
    print("=" * 60)

    # ── Step 1: Score all leads ──────────────────────────────────────
    print(f"\nScoring {len(LEADS)} leads against qualification criteria...")
    print(f"Qualification threshold: {QUALIFICATION_THRESHOLD}/100\n")

    scored_leads = []
    for lead in LEADS:
        scored = score_lead(lead)
        scored_leads.append(scored)
        status = "✓ QUALIFIED" if scored["qualified"] else "✗ DISQUALIFIED"
        print(f"  {scored['brand_name']}: {scored['qualification_score']}/100 — {status}")

    # Filter to qualified leads only.
    qualified_leads = [l for l in scored_leads if l["qualified"]]
    print(f"\n{len(qualified_leads)} of {len(LEADS)} leads qualified.")

    # ── Step 2: Research qualified leads ────────────────────────────
    print(f"\nGenerating research briefs for {len(qualified_leads)} qualified leads...")
    print("Each brief takes 10-15 seconds...\n")

    qualified_leads_with_briefs = []

    for i, lead in enumerate(qualified_leads, start=1):
        print(f"  Researching lead {i} of {len(qualified_leads)}: {lead['brand_name']}...")
        brief = generate_research_brief(lead)
        lead_with_brief = lead.copy()
        lead_with_brief["research_brief"] = brief
        qualified_leads_with_briefs.append(lead_with_brief)
        print(f"  ✓ {lead['brand_name']} research complete.")

    # ── Step 3: Save all results ─────────────────────────────────────
    print("\nSaving results...")
    save_research_results(scored_leads, qualified_leads_with_briefs)

    print("\n" + "=" * 60)
    print("LEAD RESEARCH COMPLETE")
    print(f"  {len(scored_leads)} leads scored")
    print(f"  {len(qualified_leads_with_briefs)} research briefs generated")
    print("  Run outreach_generator.py next.")
    print("=" * 60)