# promo_campaign.py
# This script generates three promotional campaign emails for FemFit.fit.
# Each campaign has a different trigger, goal, and tone.
# All three are generated in one run and saved to the outputs folder.

import anthropic
import os
from brand_voice import FEMFIT_BRAND_VOICE

# Set up the Anthropic client.
# It reads your ANTHROPIC_API_KEY system environment variable automatically.
client = anthropic.Anthropic()

# ── Campaign briefs ──────────────────────────────────────────────────────────
# Each dictionary defines one promotional campaign.
# Think of this as the creative brief you would hand to a copywriter.

promo_campaigns = [
    {
        "campaign_name": "Flash Sale",
        "campaign_type": "24-hour sitewide discount",
        "trigger": "Unplanned inventory clearance — FemFit.fit needs to move stock fast",
        "offer": "25% off everything for 24 hours — code: FEMFIT25",
        "deadline": "Ends midnight tonight",
        "target_segment": "Full list — all 8,400 subscribers",
        "key_messages": [
            "25% off everything — one day only",
            "No specific reason. Just clearing space for new stock.",
            "Midnight cutoff — no extensions"
        ],
        "primary_cta": "Shop the sale",
        "tone_note": "Urgent but not desperate. Short and punchy. Get in, make the point, get out. Under 100 words in the body."
    },
    {
        "campaign_name": "New Product Launch",
        "campaign_type": "Product launch email",
        "trigger": "FemFit.fit is launching a new leggings line called the PowerForm collection — engineered for heavy lifting",
        "offer": "Free shipping on all PowerForm orders this week only",
        "deadline": "Free shipping ends Sunday",
        "target_segment": "Engaged subscribers who have opened in the last 60 days",
        "key_messages": [
            "The PowerForm collection is here — built specifically for lifting",
            "High waist that stays put under a barbell. Fabric that moves with you, not against you.",
            "We tested these through six months of real training before they went live"
        ],
        "primary_cta": "Shop PowerForm",
        "tone_note": "Excited but controlled. Let the product details do the work. No hype words. Specific and confident."
    },
    {
        "campaign_name": "Seasonal Push",
        "campaign_type": "January training season campaign",
        "trigger": "New Year — the highest traffic period for fitness brands. FemFit.fit wants to stand out without doing a generic New Year New You campaign.",
        "offer": "15% off storewide through January — code: TRAIN25",
        "deadline": "Offer runs all of January",
        "target_segment": "Full list including lapsed subscribers",
        "key_messages": [
            "January is loud. We are not going to add to the noise.",
            "You already know why you train. You do not need a resolution to tell you.",
            "If you need new gear for the sessions ahead, we have got you covered."
        ],
        "primary_cta": "Get your January gear",
        "tone_note": "Deliberately anti-hype. This email should feel different from every other January fitness email in the inbox. Calm, direct, respectful of the reader."
    }
]


# ── Email generation function ────────────────────────────────────────────────
# Takes one campaign brief and returns Claude's generated email copy.

def generate_promo_email(campaign):
    """
    Sends a promotional campaign brief to Claude and returns the email copy.

    Parameters:
        campaign (dict): A dictionary containing the campaign brief details.

    Returns:
        str: The full promotional email copy generated by Claude.
    """

    # Build the prompt using the campaign brief.
    # Each field from the dictionary is inserted into the prompt automatically.
    user_prompt = f"""
    Write a promotional campaign email for FemFit.fit.

    CAMPAIGN NAME: {campaign['campaign_name']}
    CAMPAIGN TYPE: {campaign['campaign_type']}
    CONTEXT: {campaign['trigger']}
    
    OFFER: {campaign['offer']}
    DEADLINE: {campaign['deadline']}
    TARGET SEGMENT: {campaign['target_segment']}
    
    KEY MESSAGES TO INCLUDE:
    {chr(10).join(f"- {msg}" for msg in campaign['key_messages'])}
    
    PRIMARY CTA: {campaign['primary_cta']}
    
    TONE GUIDANCE: {campaign['tone_note']}
    
    OUTPUT FORMAT — use exactly these labels:
    SUBJECT LINE:
    PREVIEW TEXT:
    EMAIL BODY:
    CTA BUTTON TEXT:
    
    Write in second person (you/your).
    Do not add any commentary before or after the email output.
    """

    response = client.messages.create(
        model="claude-opus-4-5",
        max_tokens=1000,
        system=FEMFIT_BRAND_VOICE,
        messages=[
            {"role": "user", "content": user_prompt}
        ]
    )

    return response.content[0].text


# ── Main runner with file output ─────────────────────────────────────────────
# Generates all three campaigns, prints them to the terminal,
# and saves them to the outputs folder.

if __name__ == "__main__":

    # Create the outputs folder if it does not already exist.
    # exist_ok=True means Python will not throw an error if the folder is there already.
    os.makedirs("outputs", exist_ok=True)

    # Open the output file for writing.
    # "w" mode creates the file if it does not exist, or overwrites it if it does.
    # encoding="utf-8" handles any special characters in the output safely.
    with open("outputs/promo_campaigns_output.txt", "w", encoding="utf-8") as f:

        header = "=" * 60 + "\nFEMFIT.FIT — PROMOTIONAL CAMPAIGN GENERATOR\nGenerating 3 campaign emails...\n" + "=" * 60
        print(header)
        f.write(header + "\n")

        # Loop through each campaign brief.
        # We get both the index (i) and the campaign dictionary on each loop.
        for i, campaign in enumerate(promo_campaigns):

            campaign_header = f"\n{'=' * 60}\nCAMPAIGN {i + 1} OF {len(promo_campaigns)}: {campaign['campaign_name'].upper()}\nType: {campaign['campaign_type']}\n{'=' * 60}\n"

            print(campaign_header)
            f.write(campaign_header)

            # Generate the email for this campaign brief.
            email_copy = generate_promo_email(campaign)

            print(email_copy)
            f.write(email_copy + "\n")

            divider = f"\n{'─' * 60}\n"
            print(divider)
            f.write(divider)

    print("\n✓ Promotional campaigns saved to outputs/promo_campaigns_output.txt")