# reengagement.py
# This script generates a 3-email re-engagement sequence for FemFit.fit.
# Target: subscribers who have not opened an email in 90+ days.
# Each email uses a different strategy to win them back before
# they are removed from the active list.

import anthropic
import os
from brand_voice import FEMFIT_BRAND_VOICE

# Set up the Anthropic client.
client = anthropic.Anthropic()

# ── Re-engagement sequence briefs ────────────────────────────────────────────
# Three emails. Three different psychological approaches.
# The tone shifts from warm → direct → honest across the sequence.

reengagement_briefs = [
    {
        "email_number": 1,
        "strategy": "Soft check-in",
        "timing": "Sent to subscribers inactive for 90 days",
        "objective": "Re-open the conversation with zero pressure. Acknowledge the silence naturally without making the subscriber feel guilty. Remind them what FemFit.fit is without a hard sell.",
        "key_messages": [
            "We noticed you have been quiet — no stress, life gets busy",
            "We are still here building gear for women who train seriously",
            "No pitch today — just checking in"
        ],
        "offer": "None — this email is relationship-focused, not conversion-focused",
        "primary_cta": "See what's new at FemFit",
        "tone_note": "Warm and low-key. Like a message from someone who genuinely noticed you were gone but is not going to make it weird. No guilt. No urgency. Conversational."
    },
    {
        "email_number": 2,
        "strategy": "Value reminder",
        "timing": "Sent 7 days after Email 1 if still no open",
        "objective": "Remind the subscriber what makes FemFit.fit different from other fitness brands. Lead with brand values and product quality, not a discount. Give them a reason to care again.",
        "key_messages": [
            "FemFit.fit is not like other fitness brands in your inbox",
            "We build gear that is tested through real training — not just designed to photograph well",
            "Here is what our most loyal customers keep coming back for"
        ],
        "offer": "10% off as a quiet thank-you for staying on the list — code: COMEBACK10",
        "primary_cta": "Come back and shop",
        "tone_note": "Confident and grounded. Let the brand differentiation do the work. The discount is secondary — mention it at the end, not the top. Do not lead with the offer."
    },
    {
        "email_number": 3,
        "strategy": "Final call — honest last chance",
        "timing": "Sent 7 days after Email 2 if still no open",
        "objective": "Be completely honest. Tell the subscriber this is the last email if they do not re-engage. Give them a clear choice: stay or go. Make staying easy. Do not beg.",
        "key_messages": [
            "This is the last email we will send if you do not want to hear from us",
            "No hard feelings — inboxes are personal and we respect that",
            "If you do want to stay, just click below — we would love to keep you"
        ],
        "offer": "Final offer: 15% off if they choose to stay — code: STAYWITHUS15",
        "primary_cta": "Yes, keep me on the list",
        "secondary_cta": "No thanks, unsubscribe me",
        "tone_note": "Completely honest and calm. No drama. No guilt trip. The brand is confident enough to let people go. This email should feel respectful and final — not desperate. Short. Every word earns its place."
    }
]


# ── Email generation function ────────────────────────────────────────────────

def generate_reengagement_email(brief):
    """
    Sends a re-engagement email brief to Claude and returns the copy.

    Parameters:
        brief (dict): Dictionary containing the email brief details.

    Returns:
        str: The full re-engagement email copy generated by Claude.
    """

    # Check if this brief has a secondary CTA (only Email 3 does).
    # If the key doesn't exist in the dictionary, we use "N/A" as a default.
    # This is called .get() — it is safer than directly accessing a key
    # because it won't crash if the key is missing.
    secondary_cta = brief.get("secondary_cta", "N/A")

    user_prompt = f"""
    Write Email {brief['email_number']} of 3 in the FemFit.fit re-engagement sequence.

    STRATEGY: {brief['strategy']}
    TIMING: {brief['timing']}
    
    OBJECTIVE: {brief['objective']}
    
    KEY MESSAGES TO INCLUDE:
    {chr(10).join(f"- {msg}" for msg in brief['key_messages'])}
    
    OFFER: {brief['offer']}
    PRIMARY CTA: {brief['primary_cta']}
    SECONDARY CTA (if applicable): {secondary_cta}
    
    TONE GUIDANCE: {brief['tone_note']}
    
    OUTPUT FORMAT — use exactly these labels:
    SUBJECT LINE:
    PREVIEW TEXT:
    EMAIL BODY:
    CTA BUTTON TEXT:
    
    Keep the email body between 100 and 150 words.
    Write in second person (you/your).
    Do not add any commentary before or after the email output.
    """

    response = client.messages.create(
        model="claude-opus-4-5",
        max_tokens=1000,
        system=FEMFIT_BRAND_VOICE,
        messages=[
            {"role": "user", "content": user_prompt}
        ]
    )

    return response.content[0].text


# ── Main runner with file output ─────────────────────────────────────────────

if __name__ == "__main__":

    os.makedirs("outputs", exist_ok=True)

    with open("outputs/reengagement_output.txt", "w", encoding="utf-8") as f:

        header = (
            "=" * 60 + "\n"
            "FEMFIT.FIT — RE-ENGAGEMENT SEQUENCE GENERATOR\n"
            "Target: Subscribers inactive for 90+ days\n"
            "Generating 3-email win-back sequence...\n"
            + "=" * 60
        )
        print(header)
        f.write(header + "\n")

        for brief in reengagement_briefs:

            email_header = (
                f"\n{'=' * 60}\n"
                f"EMAIL {brief['email_number']} OF 3 — {brief['strategy'].upper()}\n"
                f"Timing: {brief['timing']}\n"
                f"{'=' * 60}\n"
            )

            print(email_header)
            f.write(email_header)

            email_copy = generate_reengagement_email(brief)

            print(email_copy)
            f.write(email_copy + "\n")

            divider = f"\n{'─' * 60}\n"
            print(divider)
            f.write(divider)

    print("\n✓ Re-engagement sequence saved to outputs/reengagement_output.txt")