import anthropic
import os
from brand_voice import FEMFIT_BRAND_VOICE

# No load_dotenv() needed — your API key is already a system environment variable.
# The Anthropic SDK will find ANTHROPIC_API_KEY automatically.
client = anthropic.Anthropic()

# ── Set up the Anthropic client ──────────────────────────────────────────────
# This creates a connection to the Claude API using your API key.
# The SDK automatically looks for an environment variable called ANTHROPIC_API_KEY.

# ── Define the welcome series briefs ────────────────────────────────────────
# This is a list of three dictionaries. Each dictionary is the brief for one email.
# Think of each brief as the instruction sheet you would hand a human copywriter.

welcome_briefs = [
    {
        "email_number": 1,
        "timing": "Sent immediately on signup",
        "objective": "Introduce the brand, make a strong first impression, and drive the first purchase with a welcome discount.",
        "key_messages": [
            "Welcome to FemFit.fit — you are in the right place",
            "We build gear for women who actually train",
            "Here is 15% off your first order as a thank you for joining"
        ],
        "offer": "15% off first order — code: FEMFIT15",
        "primary_cta": "Shop the collection",
        "tone_note": "Warm but confident. Not gushing. Like a solid first impression from someone who knows what they are doing."
    },
    {
        "email_number": 2,
        "timing": "Sent 3 days after signup",
        "objective": "Build trust through brand story and social proof. Move the subscriber from curious to confident about buying.",
        "key_messages": [
            "FemFit.fit was built by a woman who trains — not a boardroom",
            "Our customers are real women with real training schedules",
            "Here is what they say about training in FemFit gear"
        ],
        "offer": "Reminder: your 15% welcome discount is still active",
        "primary_cta": "See what our customers are saying",
        "tone_note": "Storytelling mode. Grounded and honest. Let the brand story and customer voices do the selling."
    },
    {
        "email_number": 3,
        "timing": "Sent 7 days after signup",
        "objective": "Final nudge before the welcome discount expires. Create urgency without being pushy.",
        "key_messages": [
            "Your 15% welcome discount expires in 48 hours",
            "Do not leave good gear behind",
            "Here are the pieces our customers buy first"
        ],
        "offer": "15% off — code: FEMFIT15 — expires in 48 hours",
        "primary_cta": "Claim your discount before it expires",
        "tone_note": "Direct and focused. Urgency is real, not manufactured. Short email — get in, make the point, get out."
    }
]


# ── The email generation function ────────────────────────────────────────────
# This function takes one email brief and sends it to Claude.
# It returns the full email copy that Claude generates.

def generate_welcome_email(brief):
    """
    Sends a single email brief to Claude and returns the generated email copy.
    
    Parameters:
        brief (dict): A dictionary containing the email instructions.
    
    Returns:
        str: The full email copy generated by Claude.
    """

    # Build the user prompt using the brief details.
    # We use an f-string so Python fills in the brief values automatically.
    # This is what gets sent to Claude as the task — the system prompt
    # (brand voice) stays separate and sets the context.

    user_prompt = f"""
    Write Email {brief['email_number']} of 3 for the FemFit.fit welcome series.

    TIMING: {brief['timing']}
    
    OBJECTIVE: {brief['objective']}
    
    KEY MESSAGES TO INCLUDE:
    {chr(10).join(f"- {msg}" for msg in brief['key_messages'])}
    
    OFFER: {brief['offer']}
    
    PRIMARY CTA: {brief['primary_cta']}
    
    TONE GUIDANCE: {brief['tone_note']}
    
    OUTPUT FORMAT — use exactly these labels:
    SUBJECT LINE:
    PREVIEW TEXT:
    EMAIL BODY:
    CTA BUTTON TEXT:
    
    Keep the email body between 120 and 180 words.
    Write in second person (you/your).
    Do not add any commentary before or after the email output.
    """

    # Send the request to Claude.
    # client.messages.create() is the main API call.
    # model: which version of Claude to use
    # max_tokens: the maximum length of Claude's response
    # system: the standing instructions (brand voice) — Claude reads this first
    # messages: the actual task we are giving Claude right now

    response = client.messages.create(
        model="claude-opus-4-5",
        max_tokens=1000,
        system=FEMFIT_BRAND_VOICE,
        messages=[
            {"role": "user", "content": user_prompt}
        ]
    )

    # Claude's response comes back as an object.
    # response.content is a list of content blocks.
    # We want the text from the first (and only) block.
    return response.content[0].text


# ── The main runner ──────────────────────────────────────────────────────────
# This block only runs when you execute this file directly.
# If another script imports this file, this block is skipped.

if __name__ == "__main__":

    import os

    # Create the outputs folder if it doesn't exist yet
    os.makedirs("outputs", exist_ok=True)

    # Open a file to write to — this creates the file if it doesn't exist
    with open("outputs/welcome_series_output.txt", "w", encoding="utf-8") as f:

        print("=" * 60)
        print("FEMFIT.FIT — WELCOME SERIES GENERATOR")
        print("Generating 3-email welcome sequence...")
        print("=" * 60)

        for i, brief in enumerate(welcome_briefs):

            header = f"\n{'=' * 60}\nEMAIL {brief['email_number']} OF 3 — {brief['timing'].upper()}\n{'=' * 60}\n"
            
            print(header)
            f.write(header)  # Write the header to the file

            email_copy = generate_welcome_email(brief)

            print(email_copy)
            f.write(email_copy + "\n")  # Write the email to the file

            divider = f"\n{'─' * 60}\n"
            print(divider)
            f.write(divider)

    print("\n✓ Welcome series saved to outputs/welcome_series_output.txt")